name: CI-CD-Azure

on:
  pull_request:
    types:
      - opened
      - closed
      - reopened
      - edited
    branches: ["main"]

jobs:
  Build_and_Test:
    if: github.event.pull_request.merged != false || true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Angular Build
        run: npm run build
      - name: Run Tests
        run: ng test --watch=false --browsers=ChromeHeadlessCustom

  CI:
    if: github.event.pull_request.merged == true
    needs: [Build_and_Test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Docker Login - Dockerhub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Build and push Docker
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/angular-spotify:${{ github.run_number }}
            ${{ secrets.DOCKERHUB_USER }}/angular-spotify:latest
