name: CI-CD-Azure

on:
  push:
    branches: ["main"]
  pull_request:
    types:
      - closed
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    if: github.event.pull_request.merged == true || github.event.action == 'push'
    runs-on: ubuntu-latest
    steps:
      - run: echo "teste"
        
