name: CI-CD-Azure

on:
  pull_request:
    types:
      - closed
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Docker Login - Dockerhub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
          
      
