name: CI-CD-Azure

on:
  pull_request:
    types:
      - closed
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "teste 132"
